version: '3.7'
services:
  rabbitmq:
    container_name: feeder_rabbitmq
    build:
      dockerfile: docker-compose/rabbitmq/Dockerfile
      context: ./
    ports:
      - "5672:5672"
  worker:
    container_name: feeder_worker
    build:
      dockerfile: docker-compose/worker/Dockerfile
      context: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - API_URL=http://api:5000
    volumes:
      - ./:/opt/dci-feeder:Z
  api:
    container_name: feeder_api
    build:
      dockerfile: docker-compose/api/Dockerfile
      context: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - API_DEBUG=true
    ports:
      - "5000:5000"
    volumes:
      - ./:/opt/dci-feeder:Z
  rsyncd_sshd:
    container_name: feeder_rsyncd_sshd
    build:
      dockerfile: docker-compose/rsyncd_sshd/Dockerfile
      context: ./
    ports:
      - "873:873"
      - "22:22"
    volumes:
      - ./:/opt/dci-feeder:Z
      - /home/yassine/.ssh/authorized_keys:/root/.ssh/authorized_keys
