version: '3.7'
services:
  feeder_rabbitmq:
    container_name: feeder_rabbitmq
    hostname: feeder_rabbitmq
    build:
      dockerfile: docker-compose/rabbitmq/Dockerfile
      context: ./
    ports:
      - "5672:5672"
  feeder_worker:
    container_name: feeder_worker
    hostname: feeder_worker
    build:
      dockerfile: docker-compose/worker/Dockerfile
      context: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@feeder_rabbitmq:5672//
      - API_URL=http://feeder_api:5000
    volumes:
      - ./:/opt/dci-feeder:Z
  feeder_api:
    container_name: feeder_api
    hostname: feeder_api
    build:
      dockerfile: docker-compose/api/Dockerfile
      context: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@feeder_rabbitmq:5672//
      - API_DEBUG=true
    ports:
      - "5000:5000"
    volumes:
      - ./:/opt/dci-feeder:Z
  feeder_rsyncd_sshd:
    container_name: feeder_rsyncd_sshd
    hostname: feeder_rsyncd_sshd
    build:
      dockerfile: docker-compose/rsyncd_sshd/Dockerfile
      context: ./
    ports:
      - "873:873"
      - "22:22"
    user: root
    volumes:
      - ./:/opt/dci-feeder:Z
